/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List All */
        get: operations["list_all_api_instruments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/sectors": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Sectors */
        get: operations["list_sectors_api_instruments_sectors_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{kind}/{instrument_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get One */
        get: operations["get_one_api_instruments__kind___instrument_id__get"];
        put?: never;
        post?: never;
        /** Delete One */
        delete: operations["delete_one_api_instruments__kind___instrument_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/{kind}/{instrument_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Series */
        get: operations["get_series_api_instruments__kind___instrument_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/yfinance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Yfinance */
        post: operations["add_yfinance_api_instruments_yfinance_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add Upload */
        post: operations["add_upload_api_instruments_upload_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/instruments/vol/{instrument_id}/sector": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Sector */
        patch: operations["update_sector_api_instruments_vol__instrument_id__sector_patch"];
        trace?: never;
    };
    "/api/strategies": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Strategies */
        get: operations["list_strategies_api_strategies_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/schema": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Schema */
        get: operations["get_schema_api_strategies__strategy_id__schema_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute */
        post: operations["compute_api_strategies__strategy_id__compute_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/strategies/{strategy_id}/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Compute Summary */
        post: operations["compute_summary_api_strategies__strategy_id__summary_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AddResponse */
        AddResponse: {
            instrument: components["schemas"]["Instrument"];
        };
        /** AddYfinanceRequest */
        AddYfinanceRequest: {
            /** Ticker */
            ticker: string;
            kind: components["schemas"]["InstrumentKind"];
            /** Sector */
            sector?: string | null;
        };
        /** Body_add_upload_api_instruments_upload_post */
        Body_add_upload_api_instruments_upload_post: {
            /** Label */
            label: string;
            kind: components["schemas"]["InstrumentKind"];
            /** Sector */
            sector?: string | null;
            /** File */
            file: string;
        };
        /** ChartSpec */
        ChartSpec: {
            /**
             * Id
             * @description Stable per-strategy chart identifier
             */
            id: string;
            /** Title */
            title: string;
            /**
             * Description
             * @description Short markdown caption shown under the chart title
             */
            description?: string | null;
            /**
             * Guide Md
             * @description Collapsible long-form markdown ('Plain-language guide')
             */
            guide_md?: string | null;
            /**
             * Figure
             * @description Plotly figure JSON (data + layout)
             */
            figure: {
                [key: string]: unknown;
            };
        };
        /** ColumnSpec */
        ColumnSpec: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /**
             * Format
             * @description 'text' | 'number' | 'percent' | 'ratio' | 'date'
             * @default text
             */
            format: string;
            /**
             * Align
             * @description 'left' | 'right'
             * @default left
             */
            align: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** Instrument */
        Instrument: {
            /**
             * Id
             * @description Stable identifier (filename stem or 'sp500-builtin')
             */
            id: string;
            /**
             * Label
             * @description Display label
             */
            label: string;
            kind: components["schemas"]["InstrumentKind"];
            /** Sector */
            sector?: string | null;
            /** N Rows */
            n_rows: number;
            /**
             * Min Date
             * Format: date
             */
            min_date: string;
            /**
             * Max Date
             * Format: date
             */
            max_date: string;
            /**
             * Builtin
             * @default false
             */
            builtin: boolean;
        };
        /**
         * InstrumentKind
         * @enum {string}
         */
        InstrumentKind: "vol" | "trend";
        /** InstrumentList */
        InstrumentList: {
            /** Instruments */
            instruments: components["schemas"]["Instrument"][];
        };
        /** InstrumentSeries */
        InstrumentSeries: {
            /** Id */
            id: string;
            /** Label */
            label: string;
            kind: components["schemas"]["InstrumentKind"];
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
        };
        /** Metric */
        Metric: {
            /** Key */
            key: string;
            /** Label */
            label: string;
            /** Value */
            value: number;
            /**
             * Format
             * @description 'number' | 'percent' | 'ratio' — hint for UI formatting
             * @default number
             */
            format: string;
        };
        /** SeriesPoint */
        SeriesPoint: {
            /**
             * Date
             * Format: date
             */
            date: string;
            /** Close */
            close: number;
        };
        /** StrategyListResponse */
        StrategyListResponse: {
            /** Strategies */
            strategies: components["schemas"]["StrategyMeta"][];
        };
        /** StrategyMeta */
        StrategyMeta: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Description */
            description: string;
            /**
             * Instrument Kind
             * @description 'vol' or 'trend' — what to pick
             */
            instrument_kind: string;
            /**
             * Has Summary
             * @description True if this strategy exposes a multi-instrument summary endpoint
             * @default false
             */
            has_summary: boolean;
        };
        /** StrategyResult */
        StrategyResult: {
            /**
             * Overview Md
             * @description Strategy-level markdown shown above all tabs
             */
            overview_md?: string | null;
            /**
             * Metrics
             * @description Global metric strip shown above tabs
             */
            metrics?: components["schemas"]["Metric"][];
            /** Tabs */
            tabs?: components["schemas"]["TabSpec"][];
            /** Warnings */
            warnings?: string[];
        };
        /** TabSpec */
        TabSpec: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Icon */
            icon?: string | null;
            /**
             * Intro Md
             * @description Top-of-tab markdown (usually the 'Plain-language summary' guide)
             */
            intro_md?: string | null;
            /** Metrics */
            metrics?: components["schemas"]["Metric"][];
            /** Charts */
            charts?: components["schemas"]["ChartSpec"][];
            /** Tables */
            tables?: components["schemas"]["TableSpec"][];
        };
        /** TableSpec */
        TableSpec: {
            /** Id */
            id: string;
            /** Title */
            title: string;
            /** Description */
            description?: string | null;
            /** Columns */
            columns: components["schemas"]["ColumnSpec"][];
            /** Rows */
            rows: {
                [key: string]: unknown;
            }[];
        };
        /** UpdateSectorRequest */
        UpdateSectorRequest: {
            /** Sector */
            sector: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_all_api_instruments_get: {
        parameters: {
            query: {
                kind: components["schemas"]["InstrumentKind"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentList"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_sectors_api_instruments_sectors_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
        };
    };
    get_one_api_instruments__kind___instrument_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["InstrumentKind"];
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_one_api_instruments__kind___instrument_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["InstrumentKind"];
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_series_api_instruments__kind___instrument_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                kind: components["schemas"]["InstrumentKind"];
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstrumentSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_yfinance_api_instruments_yfinance_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddYfinanceRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_upload_api_instruments_upload_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_add_upload_api_instruments_upload_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AddResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_sector_api_instruments_vol__instrument_id__sector_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                instrument_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateSectorRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Instrument"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_strategies_api_strategies_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyListResponse"];
                };
            };
        };
    };
    get_schema_api_strategies__strategy_id__schema_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_api_strategies__strategy_id__compute_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compute_summary_api_strategies__strategy_id__summary_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                strategy_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    [key: string]: unknown;
                };
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StrategyResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
